import { useState } from 'react'
import { generateGapReport } from '../lib/gapReport'
import { downloadTextFile } from '../lib/download'
import { hasApiKey } from '../lib/anthropicClient'

export default function GapReportPanel({ company, checklist, pdfFindings }) {
  const [report, setReport] = useState(null)
  const [status, setStatus] = useState('idle') // idle | generating | done

  async function handleGenerate() {
    setStatus('generating')
    const result = await generateGapReport({ company, checklist, pdfFindings })
    setReport(result)
    setStatus('done')
  }

  function handleDownload() {
    if (!report) return
    const filename = `${company.name.replace(/\s+/g, '_')}_AI_Disclosure_Gap_Report.txt`
    downloadTextFile(filename, report.text)
  }

  return (
    <div className="section">
      <div className="section-title">Full Gap Report</div>

      {!hasApiKey && (
        <div className="warning-banner" style={{ marginBottom: 14 }}>
          VITE_ANTHROPIC_API_KEY is not set — generating a locally computed report instead of a
          Claude-authored one.
        </div>
      )}

      <div className="report-actions">
        <button className="btn-primary" type="button" onClick={handleGenerate} disabled={status === 'generating'}>
          {status === 'generating' ? (
            <>
              <span className="spinner" /> Generating…
            </>
          ) : (
            'Generate Gap Report'
          )}
        </button>
        <button className="btn-ghost" type="button" onClick={handleDownload} disabled={!report}>
          Download as .txt
        </button>
      </div>

      {report && (
        <div className="report-panel">
          <span className="report-source-tag">
            {report.source === 'claude' ? `Generated by Claude (${'claude-sonnet-4-6'})` : 'Locally generated estimate'}
            {report.error ? ` — Claude call failed: ${report.error}` : ''}
          </span>
          <pre className="report-text">{report.text}</pre>
        </div>
      )}
    </div>
  )
}
